# Project information
site_name: Git For Colleagues
site_author: Laurens van der Tas
site_description: To the point guide for colleagues for using Git.
repo_name: git_for_colleagues
copyright: Copyright &copy; 2023 Laurens van der Tas
repo_url: https://github.com/LPvdT/git-for-colleagues
site_url: https://lpvdt.github.io/git-for-colleagues/

# Page tree
nav:
  - Git For Colleagues:
      - index.md
      - The Git Repository:
          - git_repository/index.md
          - git_repository/working_staging_repo.md
          - git_repository/status.md
      - Commits:
          - commits/index.md
          - commits/staging.md
          - commits/committing.md
          - commits/difference.md
      - Branches:
          - branches/index.md
          - branches/creating_switching.md
          - branches/merge_rebase.md
          - branches/cherry_picking.md
      - Revert & Reset:
          - revert_reset/index.md
          - revert_reset/revert_reset.md
          - revert_reset/head.md
      - Stash:
          - stash/index.md
      - Remote Repositories:
          - remote_repos/index.md
          - remote_repos/clone_fork.md
          - remote_repos/remote_branches.md
          - remote_repos/fetch_pull_push.md
          - remote_repos/pull_requests.md
          - remote_repos/merge_conflicts.md
      - Best practices & Design:
          - design_best_practices/index.md
          - design_best_practices/best_practices.md
          - design_best_practices/design.md
          - design_best_practices/tools.md
      - Next steps:
          - next_steps/index.md
          - next_steps/tutorials_projects.md

# Configuration
theme:
  name: material
  language: en
  features:
    - content.code.annotate
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Barlow
    code: JetBrains Mono
  icon:
    logo: logo
  favicon: assets/images/favicon.png

# Plugins
plugins:
  - search
  - offline
  - glightbox:
      touchNavigation: true
      effect: zoom
      slide_effect: slide

# Extra
extra:
  generator: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
